from __future__ import annotations

import json
import re
from typing import Any

from .models import DeviceDescriptor, to_jsonable


def build_exports(devices: list[DeviceDescriptor]) -> dict[str, str]:
    exports: dict[str, str] = {}
    role_counts: dict[str, int] = {}

    for device in devices:
        role = sanitize_role(device.role or device.kind)
        role_counts[role] = role_counts.get(role, 0) + 1
        if not device.role and role_counts[role] > 1:
            role = f"{role}_{role_counts[role]}"

        prefix = f"HURRY_{role.upper()}"
        if device.kind == "serial" and device.stable_path:
            exports[f"{prefix}_PORT"] = device.stable_path
        elif device.kind == "gamepad" and device.stable_path:
            exports[f"{prefix}_DEV"] = device.stable_path
        elif device.locality == "lan" and device.address:
            exports[f"{prefix}_HOST"] = device.address
            ports = device.metadata.get("open_ports") or device.metadata.get("configured_ports")
            if ports:
                exports[f"{prefix}_PORTS"] = ports
        elif device.bus_id:
            exports[f"{prefix}_BUSID"] = device.bus_id

    return exports


def render_exports(devices: list[DeviceDescriptor], output_format: str) -> str:
    exports = build_exports(devices)
    if output_format == "json":
        return json.dumps({"exports": exports, "devices": to_jsonable(devices)}, indent=2, sort_keys=True)
    if output_format == "yaml":
        try:
            import yaml

            return yaml.safe_dump({"exports": exports, "devices": to_jsonable(devices)}, sort_keys=True)
        except ImportError:
            return json.dumps({"exports": exports, "devices": to_jsonable(devices)}, indent=2, sort_keys=True)
    if output_format == "launch":
        return "\n".join(f"{key_to_launch_arg(key)}:={value}" for key, value in sorted(exports.items()))
    if output_format == "params":
        return render_params_file(exports)
    if output_format == "launch-file":
        return render_launch_file(exports)
    return "\n".join(f"export {key}={shell_quote(value)}" for key, value in sorted(exports.items()))


def render_params_file(exports: dict[str, str]) -> str:
    params = build_ros_parameters(exports)
    if not params:
        return "/**:\n  ros__parameters: {}\n"

    lines = ["/**:", "  ros__parameters:"]
    for key, value in sorted(params.items()):
        if isinstance(value, list):
            lines.append(f"    {key}:")
            for item in value:
                lines.append(f"      - {format_yaml_scalar(item)}")
        else:
            lines.append(f"    {key}: {format_yaml_scalar(value)}")
    return "\n".join(lines) + "\n"


def render_launch_file(exports: dict[str, str]) -> str:
    if not exports:
        return "\n".join(
            [
                "# Generated by hurry-porter. Regenerate after hardware changes.",
                "from launch import LaunchDescription",
                "",
                "",
                "def generate_launch_description():",
                "    return LaunchDescription([])",
                "",
            ]
        )

    lines = [
        "# Generated by hurry-porter. Regenerate after hardware changes.",
        "from launch import LaunchDescription",
        "from launch.actions import DeclareLaunchArgument, SetEnvironmentVariable",
        "from launch.substitutions import LaunchConfiguration",
        "",
        "",
        "def generate_launch_description():",
        "    return LaunchDescription([",
    ]
    for env_key, value in sorted(exports.items()):
        arg_name = key_to_launch_arg(env_key)
        lines.extend(
            [
                "        DeclareLaunchArgument(",
                f"            {python_string(arg_name)},",
                f"            default_value={python_string(value)},",
                f"            description={python_string(f'Generated by hurry-porter from {env_key}.')},",
                "        ),",
                "        SetEnvironmentVariable(",
                f"            name={python_string(env_key)},",
                f"            value=LaunchConfiguration({python_string(arg_name)}),",
                "        ),",
            ]
        )
    lines.extend(["    ])", ""])
    return "\n".join(lines)


def build_ros_parameters(exports: dict[str, str]) -> dict[str, Any]:
    return {key_to_launch_arg(key): coerce_parameter_value(key, value) for key, value in exports.items()}


def key_to_launch_arg(key: str) -> str:
    return key.lower().removeprefix("hurry_")


def coerce_parameter_value(key: str, value: str) -> str | list[int] | list[str]:
    if key.endswith("_PORTS") and "," in value:
        parts = [part.strip() for part in value.split(",") if part.strip()]
        if all(part.isdigit() for part in parts):
            return [int(part) for part in parts]
        return parts
    return value


def sanitize_role(value: str) -> str:
    sanitized = re.sub(r"[^a-zA-Z0-9]+", "_", value).strip("_").lower()
    return sanitized or "device"


def shell_quote(value: str) -> str:
    if re.match(r"^[A-Za-z0-9_./:@,+-]+$", value):
        return value
    return "'" + value.replace("'", "'\"'\"'") + "'"


def format_yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    return json.dumps(str(value))


def python_string(value: str) -> str:
    return json.dumps(value)
